CREATE TABLE courses (
  course_id BIGSERIAL PRIMARY KEY,
  code      VARCHAR(30) UNIQUE NOT NULL,
  title     VARCHAR(160) NOT NULL,
  level     VARCHAR(20) NOT NULL CHECK (level IN ('BEGINNER','INTERMEDIATE','ADVANCED')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);