with open("M4/L6/D1/data/reporte.txt", "w", encoding="utf-8") as f:
    f.write("=====================================\n")
    f.write("            BOLETA DE VENTA           \n")
    f.write("=====================================\n")
    f.write("Empresa   : Blandskron SpA\n")
    f.write("RUT       : 77.123.456-9\n")
    f.write("Fecha     : 15-01-2025\n")
    f.write("Hora      : 14:32\n")
    f.write("-------------------------------------\n")
    f.write("Detalle de productos\n")
    f.write("-------------------------------------\n")
    f.write("1  Curso Python Básico      $ 5.990\n")
    f.write("1  Curso Django Web         $ 7.990\n")
    f.write("2  Curso IA Aplicada        $ 3.990\n")
    f.write("-------------------------------------\n")
    f.write("Subtotal                  $21.960\n")
    f.write("IVA (19%)                  $4.172\n")
    f.write("-------------------------------------\n")
    f.write("TOTAL A PAGAR              $26.132\n")
    f.write("-------------------------------------\n")
    f.write("Método de pago : Tarjeta Débito\n")
    f.write("Código venta   : VT-2025-000123\n")
    f.write("=====================================\n")
    f.write("        Gracias por su compra         \n")
    f.write("=====================================\n")
